# Generated by Django 3.1.3 on 2020-11-25 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UrlCompany', models.URLField()),
                ('CompanyName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAndUsername', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('firstName', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profession', models.CharField(max_length=128)),
            ],
        ),
    ]
